AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'gov-test-awssam-${AWS::AccountId}-${AWS::Region}'  # Dynamically generated bucket name using account ID and region
      # For regions other than 'us-east-1', uncomment the below and set the region accordingly
      # LocationConstraint: us-west-2  # Specify the correct region

