AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-awssam-oidc  # Use the bucket name from the environment variable
#      Region: us-east-1  # Make sure the region is set to a valid AWS region

